scripts/check-clippy.sh, scripts/check-nightly.sh, sdk/Cargo.toml
The `dummy-for-ci-check` feature was added to avoid breaking Agave's CI when the sdk was put into its own workspace, but it isn't actually needed by `solana-sdk` now that it's out of the Agave repo.
Remove the feature everywhere.
=> sdk: Remove dummy-for-ci-check feature

loader-v3-interface/src/instruction.rs, program/src/bpf_loader_upgradeable.rs
The SDK changes from https://github.com/anza-xyz/agave/pull/4661 need to be applied here.
See [SIMD-0167](https://github.com/solana-foundation/solana-improvement-documents/pull/167).
Feature Gate Issue: https://github.com/anza-xyz/feature-gate-tracker/issues/78
Once this lands, we can publish v3.0.0 of the crate to be used by Agave
=> loader-v3: Add `UpgradeableLoaderInstruction::Migrate`

account/src/lib.rs
In order to create a lightweight view struct (https://github.com/anza-xyz/agave/pull/4834) over vote account data without creating another copy of the data, I need to copy the internal `Arc` which is private.
=> solana-account: add AccountSharedData::data_clone method

.github/workflows/main.yml
#9 introduced a breaking change to the loader-v3-interface crate, but the downstream job is still running.
Until agave is updated to use the newest version of loader-v3-interface, disable the downstream job.
=> CI: Disable downstream job temporarily

.gitignore
Some of the tests in this repo create a `farf/` directory, but it isn't included in the `.gitignore`, so they show up in the git diff.
Add `farf/` to .gitignore
=> Add `farf/` directory to .gitignore

ed25519-program/src/lib.rs
follow up from https://github.com/solana-program/slashing/pull/5#discussion_r1918588583
we add an instruction builder for doing multiple signature verifications in one verify instruction and expose a helper function.
=> ed25519: add instruction builder for multiple verifications

Cargo.toml
All of the crates within solana-sdk pin their dependency on intra-workspace crates, ie `solana-program` uses version `=2.2.0` of `solana-pubkey`. This is a holdover from Agave, where it makes sense to pin everything to be sure that you're getting exactly what you expect.
Also, since Agave crates do not always adhere to semver, pinning the local dependencies ensures that the build always works as expected.
Since crates are versioned independently within the solana-sdk repo, however, the pinning requires us to publish all downstream crates anytime one of them is updated, to be sure that a build is possible. This is onerous and unnecessary, since solana-sdk will adhere to semver going forward.
Relax all of the dependencies to remove the `=`.
Note that we will need to bump all crates to …
=> workspace: Relax intra-workspace dependencies

.github/workflows/main.yml
Similar to https://github.com/anza-xyz/agave/pull/4944, we need to update the openssl version used in CI.
Also, I noticed some failing commands from a recent run.
Update to openssl 3.4.1, and fixup those commands.
=> CI: Fix windows clippy job

.github/CODEOWNERS
- @anza-xyz/tx-metadata owns crates in agave related to transaction parsing/validation
- If the `sdk` crates for message/transaction deserialization and validation become inconsistent it would be bad for the network
- We'd like someone from the team to review any changes to these crates to avoid accidental breakage 
- Create .github/CODEOWNERS file
- Add @anza-xyz/tx-metadata as owner of `message` and `transaction` crates
=> set CODEOWNERS for message and transaction crates

Cargo.lock, Cargo.toml, feature-set/Cargo.toml
The auto-publish job for v2.2.2 had a bug in it during run https://github.com/anza-xyz/solana-sdk/actions/runs/13297445413/job/37132523790 and wasn't able to push the updated version to the repo.
Update the version manually.
=> feature-set: Bump to v2.2.2

vote-interface/src/state/mod.rs
The commission split logic should live in the runtime rather than the sdk in my opinion. I need to use this logic on a new runtime vote state view type introduced in https://github.com/anza-xyz/agave/pull/4834 without creating an instance of a `VoteState`. The logic will be moved into the runtime here: https://github.com/anza-xyz/agave/pull/4876. Rather than keeping two copies of this logic, let's deprecate and remove the method here since I don't think it's that useful to clients.
=> solana-vote-interface: deprecate VoteState::commission_split

quic-definitions/src/lib.rs
This is to resurrect the PR https://github.com/anza-xyz/agave/pull/4585 which was reverted due to CI failure.
The CI failure has been root caused due to defunct connections being used for longtime before the increased idle timeout value: https://github.com/anza-xyz/agave/pull/4841. 
For backward compatibility the QUIC_KEEP_ALIVE is kept as the old one -- to be increased once the network is upgraded to having the higher IDLE_TIMEOUT
=> increased quic connection timeout

compute-budget-interface/src/lib.rs
This macro currently assumes that core::mem::size_of is in scope
=> use fully qualified path in to_instruction macro

rust-toolchain.toml
The rust version used by this repo is still on v1.84.0, despite agave being on v1.84.1.
Bump it to v1.84.1
=> rust: Bump version to 1.84.1

bn254/Cargo.toml, logger/Cargo.toml, program/Cargo.toml, sdk/Cargo.toml
Some crates are including useless extras in what gets uploaded to crates.io, such as benchmarks and test directories. `cargo diet` is a tool to remove this stuff by specifying a minimal `include` field in Cargo.toml.
I ran `find . -type f -name "Cargo.toml" -execdir cargo diet \;` and then removed the change for `solana-logger` because it made no difference to what I saw when I ran `cargo package -l`
=> run cargo diet on all crates

.github/dependabot.yml
Dependabot updates all versions of packages, which is less flexible for end users. This made sense for agave, which is focused on providing a binary, but libraries are more useful when dependencies are relaxed.
Change the open pull request number to 0 to only enable security updates, as documented at
[Dependabot's documentation](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file)
Fixes #55
cc @kevinheavey
=> CI: Only get security updates

feature-set/src/lib.rs
`solfuzz-agave` uses the feature set defined here to create a list of supported features for fuzzing. Without this change, we cannot add this feature to our supported features list. This is also the only non-public feature that was made private when the feature was cleaned up from the codebase.
=> Make `revise_turbine_epoch_stakes` feature public 

Cargo.lock, Cargo.toml, logger/Cargo.toml, logger/src/lib.rs, scripts/check-nits.sh
redirect_stderr_to_file can be used multiple applications. I found the need to use it in vortexor. Moving this from validator to solana-logger.
Refactored from https://github.com/anza-xyz/agave/blob/master/validator/src/lib.rs#L39 which will be removed once this change made to the SDK
=> Refactor redirect_stderr_to_file to solana-logger

logger/src/lib.rs
Ran into a comp issue on Windows platform:
140 |                 setup_file_with_default(&logfile, solana_logger::DEFAULT_FILTER);
|                                                   ^^^^^^^^^^^^^ use of undeclared crate or module `solana_logger`
Maybe we should add windows comp/clippy checks?
=> Fix a windows compilation issue

.github/workflows/main.yml
The windows CI job doesn't seem to be doing anything, likely because the clippy run step doesn't specify to run it under bash. See a no-op run at https://github.com/anza-xyz/solana-sdk/actions/runs/13663660460/job/38200289091
Run the script under bash rather than the default shell.
NOTE: This should fail CI until #66 lands
=> CI: Run clippy script in bash

Cargo.toml
Right now, the publish job uses a default message for the commit and tag message of `chore: Release`, which isn't very descriptive, especially when there are many possible crates to release.
Similar to what was done at SPL, configure `cargo-release` to use a better tag and commit message.
Here's an example commit:
https://github.com/solana-labs/solana-program-library/commit/a85d36141d639da42fb5f9163ca6aadfc60d8326
=> CI: Update commit message for cargo-release

signature/src/lib.rs
It would be nice to have access to the inner array in `Signature` (same as `Pubkey::as_array`) to use custom encoder such as five8
=> add Signature::as_array

Cargo.lock
There's an audit issue on ring versions below 0.17.12.
Bump ring to 0.17.13.
=> audit: Update ring to 0.17.13

pubkey/src/lib.rs
`From<&Pubkey>` is required for the `EntryRef::insert` [trait bounds](https://docs.rs/hashbrown/latest/hashbrown/hash_map/enum.EntryRef.html#method.insert) in the hashbrown crate.
=> feat: add `From<&Pubkey> for Pubkey`

Cargo.lock, Cargo.toml, feature-set-interface/Cargo.toml, feature-set-interface/src/lib.rs
step one of monorepo reclaiming the feature-set
this takes a copy of all generic symbols from solana-feature-set. we will wrap it in a new crate with the agave/cluster-specific symbols declared
possible that we don't want this at all and should just take a full copy back to monorepo
=> add solana-feature-set-interface crate

vote-interface/src/instruction.rs
`create_account_with_config` did not properly support account creation using a seed, even though it was intended to. The function now correctly checks for the presence of a seed in `config.with_seed` and calls `create_account_with_seed` when applicable.
Closes https://github.com/anza-xyz/agave/pull/2819
=> Fix vote account creation with seed

ed25519-program/src/lib.rs
Users of `solana-ed25519-program` need to manually create the offsets to support verifying multiple signatures so the fields need to be public.
=> solana-ed25519-program: make offset fields public

.github/workflows/publish-rust.yml
The publish job failed recently because a commit landed *after* the job was started at
https://github.com/anza-xyz/solana-sdk/actions/runs/14089935529/job/39463977139
This happened because the job has an out-of-date view of the repo.
Similar to how this was done in SPL, rebase before publish.
=> CI: Add rebase step during publish

sdk/src/lib.rs
The following `solana_sdk` modules should no longer be consumed by anyone and are now marked as deprecated
- `precompiles`
- `feature_set`
- `reserved_account_keys`
Both the `feature_set` and `reserved_account_keys` were attempted to be marked as deprecated in the past but adding deprecation annotations to a re-export of a crate does not work. This change puts those re-exports inside a deprecated module so that consumers actually receive the deprecation notice. The other broken deprecation annotations are left as an exercise to anyone who cares to fix it ;)
=> solana-sdk: deprecate modules migrated to agave

feature-set-interface/src/lib.rs
turns out `solana-feature-set-interface` was a bad idea after all. let's kill it before it takes root
=> deprecate `solana-feature-set-interface` crate

pubkey/Cargo.toml, pubkey/src/lib.rs
Pubkey struct already contains random bytes, and is very commonly a key in a `HashMap`. Hashing pubkeys for hashmap purposes is not useful since they are already effectively random, so just picking a slice will do the trick.
Idea was proposed by @alessandrod to make some of the hashmap-intensive code a little bit faster. Hashing is not *the* bottleneck by any means, but there is truly no point doing useless work.
Implemenation notes:
- the custom Hash implementation prevents the hasher from consuming the length (which is always 32 so no point hashing it anyway)
- The custom hasher is not used by default, one needs to manually build HashMap with it to activate, so it will not break existing code
- The changes to new_unique() are needed to prevent the pubkeys that are full of zeros from …
=> Add null hasher for Pubkey

message/src/compiled_keys.rs
Before clusters adop https://github.com/solana-foundation/solana-improvement-documents/pull/242, we should ensure that no transactions are inadvertently loading nonces from ALT's
=> message: don't use nonces from alt's

Cargo.toml, scripts/publish-rust.sh
The sdk repo respects semver, but still bumps intra-repo versions any time one of them gets published. This requires downstream users to use all of the newest versions at once, which may not be desirable.
Bump down all of the intra-repo dependency versions to v2.2.1, which is the first version that relaxed all dependencies too.
NOTE: solana-address-lookup-table-interface was a special case, and needs to stay on v2.2.2 to benefit from relaxed dependencies.
At the same time, use the `--dependent-version fix` flag in cargo release, which avoids bumping the intra-repo dependency during a publish. Thankfully, cargo-release does the right thing and *will* bump the intra-repo dependency if it's a major release.
=> deps: Bump down intra-repo dependencies

program-error/src/lib.rs, program/src/program_error.rs
As part of the breaking change to unite pinocchio's program error with the sdk's program error in #12, we are introducing a new `ToStr` trait that doesn't rely on any particular logging.
To go with that, we want to deprecate `PrintProgramError`.
Before landing the breaking change, let's deprecate `PrintProgramError` properly and add `ToStr` as an alternative for downstream users.
Once this lands, we'll do the patch release with the deprecation, then we can finally land #12.
cc @kevinheavey
=> program-error: Deprecate PrintProgramError

vote-interface/src/state/mod.rs
The default behavior in the vote lockouts calculation is to panic on larger confirmation counts. This case never gets hit in production / mainnet, but our fuzzers often hit this case when fuzzing at the instruction / transaction level and providing arbitrary confirmation counts within the account data. Since this case is incredibly difficult to prevent in the fuzzer's mutations, we choose to handle this behavior more gracefully by avoiding the panic due to overflow.
=> vote: Use wrapping pow with min lockout history in `lockout()` calculation

pubkey/src/lib.rs
If the `std` feature is disabled on `solana-pubkey`, there's currently a warning in the build due to a variable that doesn't need to be marked as `mut`.
Gate marking the variable as `mut` depending on the feature / target. Also, we already pull in the std crate earlier if the `std` feature is enabled, so we don't need to do it twice.
=> pubkey: Don't always mark variable as mut

ed25519-program/src/lib.rs, keypair/Cargo.toml, keypair/src/lib.rs, signature/Cargo.toml, signature/src/error.rs, signature/src/lib.rs
The keypair, signature, and ed25519-program crates all expose `ed25519_dalek` types in their public APIs, either as inputs or outputs.
This makes it difficult to land PRs like #26, since we'll just end up causing breaking changes.
Rather than constantly break APIs whenever the ed25519_dalek crates publishes a new major version, deprecate all functions that use ed25519_dalek types and add non-dalek versions.
* 128d5e45043ac25517b52d968d3a4b9ed42216a0: ed25519-program changes
* 87f76f5b53aab128e65a0637341ab4e52d5fa7e3: new Signature error type
* c5be15e499c8841315852b3d2802b6b8f8da53ed: keypair changes
As part of this work, I copied over the Signature error from RustCrypto to use as a generic error. That way, we can choose when to make breaking changes, independent of dependency bumps. I …
=> keypair / signature / ed25519: Deprecate dalek types from public API

.github/workflows/main.yml, message/Cargo.toml, scripts/check-powerset.sh, signature/src/error.rs, sysvar/src/slot_hashes.rs
As pointed out in #108, we don't explicitly check for all combinations of features in the sdk, and more specifically, we miss warnings.
Add a CI step to run `cargo clippy -- --deny=warnings` on the powerset of features in the sdk. Currently, this means 888 different crate builds, but most of them are quite short.
Let's see how long it takes to run in CI to see if it's worth adding.
Also, fix some little issues that came up while running this.
=> CI: Add powerset clippy check

rust-toolchain.toml
Rust v1.85.1 is now available, but the sdk repo is still on 1.84.1
Bump the version declared in rust-toolchain.toml
=> Bump stable rust version to 1.85.1

.github/workflows/main.yml, scripts/check-hack.sh, scripts/check-nightly.sh
We've been adding a lot of new CI steps to the SDK, but some of them might be redundant, causing us to use more CI resources than necessary.
For example, we run `./cargo nightly check` and `./cargo nightly hack check`. Are both of those really necessary?
Remove the nightly check CI job and script, and add some of those features and flags to the hack check.
NOTE: I'm not 100% sure about this, so let me know what you think!
=> CI: Remove nightly check, add more to hack check

file-download/src/lib.rs, genesis-config/src/lib.rs, keypair/src/lib.rs, loader-v3-interface/src/instruction.rs, precompiles/src/lib.rs, scripts/rust-version.sh, serde-varint/src/lib.rs, transaction/src/lib.rs
The stable toolchain was bumped to 1.85.1, but the nightly toolchain is still behind.
Update the nightly version to 2025-04-01 and fix issues that come up.
* io::Error::new(io::ErrorKind::Other ...) -> io::Error::other
* map_or(true, ...) -> is_none_or
* identation fixes
* using div_ceil
I wasn't sure what version Agave would land on, so let me konw if I should use another one.
=> rust: Bump nightly to 2025-04-01

Cargo.lock, secp256k1-program/Cargo.toml, secp256k1-program/src/lib.rs
The libsecp256k1 crate used by the secp256k1-program is unmaintained, but its types appear in the public API of the crate, so we can't upgrade or change the library without breaking users.
Abstract away the usage of libsecp256k1 by introducing new generic functions that simply take in byte arrays.
=> secp256k1: Deprecate libsecp256k1 from public interface

pubkey/src/lib.rs
Resolves https://github.com/anza-xyz/solana-sdk/issues/124
The crate misses core::mem::size_of (or std) causing build failures when other dependencies require it. Add import to resolve, opting for `core` as opposed to `std` such that it works with existing `#![no_std]` declaration.
As part of upgrading to anchor 0.31.0 and solana 2.x
=> pubkey: fix compile error by importing size_of

Cargo.lock, Cargo.toml
This update addresses the advisory:
https://rustsec.org/advisories/RUSTSEC-2025-0022
=> chore: Update `openssl` to 0.10.72 and `openssl-sys` to 0.9.107

Cargo.lock, Cargo.toml, frozen-abi/Cargo.toml, frozen-abi/src/abi_example.rs
Currently it's impossible to use `Bytes` in ABI-stable types. Allow that by adding the necessary `AbiExample` implementation.
=> frozen-abi: Add `AbiExample` implementation for `bytes::Bytes`

.github/actions/setup/action.yml, .github/workflows/main.yml, cargo, pubkey/src/lib.rs, scripts/check-msrv.sh, scripts/rust-version.sh, signature/src/error.rs
We broke pubkey by assuming that `size_of` was included in the prelude, which was added after 1.79, the minimum supported rust version for solana-program. This happened because we're not explicitly testing the minimum supported rust version in crates that expose it.
More info at #124
Add a "minimum" toolchain in the repo, and add a CI step + script to check that `cargo check` passes for this toolchain.
While working on this, I found a few more places that were broken, so fix those up.
=> CI: Add minimum supported rust version check

scripts/patch-crates-functions.sh
As noted in #121, the patching script in this repo doesn't work on Agave v2.2, because solana-transaction-context was moved back into the Agave repo, but the script is still trying to patch it.
Remove transaction-context from one of the scripts to patch. This is one part of fixing the issue.
=> scripts: Fix downstream patch script

secp256r1-program/src/lib.rs
This is #114, but for secp256r1 instead, removing external types from the public interface.
This one was a bit more complicated because it uses openssl types, which aren't as straightforward as simple bytes, so it uses bytes encoded in DER as the interface. This seemed like the most standard format from simple web searching, but I'm certainly no expert in this area.
There seemed to also be a lot of vecs in the new instruction implementation, which shouldn't be necessary, so I changed those to arrays.
=> secp256r1: Deprecate openssl types in public API

.github/workflows/main.yml, Cargo.toml, scripts/build-sbf.sh, scripts/check-build-sbf.sh
In general, the workspace rust toolchain has a different (newer) version than the built-in one used by `build-sbf`. This could potentially lead to compilation problems not currently detected by the CI when using crates in a program context – e.g., #124.
Add a "check-build-sbf" step to the CI to build crates using `cargo build-sbf`.
Fixes #70
=> ci: Add build-sbf step

vote-interface/src/state/mod.rs, vote-interface/src/state/vote_instruction_data.rs
For some odd reason, all of the vote instruction data types are in the `state` module. This just moves them to a new sub module to declutter the `state/mod.rs` file and avoids making any breaking changes
=> vote-interface: move vote ix data types to new module

scripts/test-miri.sh
The miri job is assuming that the `hash` module and the `account_info` module in `solana-program` have tests, but those were moved into `solana-hash` and `solana-account-info` awhile ago.
Specify the correct packages to test.
=> CI: Fix miri job to actually run tests

.github/scripts/add-team-to-ghsa.sh, .github/workflows/add-team-to-ghsa.yml
The sdk has security advisories enabled, but there's no job to automatically add the security incident teams to them.
Copy the scripts from the agave repo and rename `agave` to `solana-sdk` everywhere.
This will require `secrets.GHSA_ADD_SECURITY_INCIDENT_RESPONSE`, and I'm not sure if that's a repo secret or an org secret -- it might be easier to make it an org secret if it isn't setup that way already.
=> CI: Add scripts for GHSA management

program-entrypoint/src/lib.rs
Currently, the `entrypoint_no_alloc` macro uses `AccountInfo` and `Pubkey` types, which requires the client code to make them available to avoid compilation errors.
Export `AccountInfo` and `Pubkey` types and qualified their use in the macro with `$crate::`.
=> program-entrypoint: Export used types by no_alloc macro

.github/workflows/sysvar-comment.yml, sysvar/src/lib.rs
As noted at
https://github.com/anza-xyz/agave/pull/428#issuecomment-2795213465, it's possible to update the Rust client and forget to update the JS client.
Copy the solution at https://github.com/orgs/community/discussions/69944#discussioncomment-10796276, but adapt it to our needs.
~~NOTE: I'll try updating some paths to see if this works.~~ Testing failed, oh well
=> CI: Add a comment if a PR touches sysvars

Cargo.lock, decode-error/src/lib.rs, precompile-error/src/lib.rs, program-error/src/lib.rs, program/src/address_lookup_table.rs, program/src/bpf_loader_upgradeable.rs, program/src/lib.rs, program/src/loader_v4.rs, program/src/nonce.rs, program/src/stake.rs, program/src/stake_history.rs, program/src/system_instruction.rs, program/src/system_program.rs, pubkey/src/lib.rs, sdk/src/feature.rs, sdk/src/lib.rs, sdk/src/program_utils.rs, sdk/src/rpc_port.rs, transaction/Cargo.toml, transaction/src/sanitized.rs, vote-interface/src/error.rs
There are many different crates and types that we would like to remove from the sdk, but they are still re-exported from solana-sdk and solana-program. The re-exports have a `#[deprecated(...)]` attribute, but they aren't flagged to downstream users.
Make the re-export deprecations louder by creating a deprecated module and re-exporting from in there.
These are the types affected
* `DecodeError`: this trait isn't all that useful, and is set to be removed entirely with #104, so deprecate it here
These are the crates to no longer re-export from solana-program because they will be moved to program-specific repos:
* `address_lookup_table` -> `solana_address_lookup_table_interface`
* `bpf_loader_upgradeable` -> `solana_loader_v3_interface`
* `loader_upgradeable_instruction` -> …
=> Deprecate re-exports more loudly

loader-v3-interface/src/instruction.rs
For [SIMD-0164](https://github.com/solana-foundation/solana-improvement-documents/pull/164).
=> Feature - Adds `UpgradeableLoaderInstruction::ExtendProgramChecked`

message/src/legacy.rs
legacy: use saturating_sub in is_writable_index()
Fixes #150.
Problem
-------
`is_writable_index()` subtracts two u8 header counters.  
If the caller skips `Message::sanitize()` the subtraction can underflow, panicking in debug builds or silently wrapping to 255 in release, making ≈all accounts appear writable.
Options considered
------------------
* wrapping_sub  
+ Zero-cost.  
- Fail-open: an unchecked message marks many indices writable.
* saturating_sub (chosen)  
+ Matches the [v0-message implementation](https://github.com/anza-xyz/solana-sdk/blob/0f9989d0f2f6aa5328124084e20f587446bda79b/message/src/versions/v0/loaded.rs#L116-L136).  
+ Fail-closed: underflow clamps to 0, no extra accounts are writable.  
- Adds a micro-op, but this should cause no performance impact.
Change
------ …
=> use saturating_sub in is_writable_index() - fix #150

loader-v3-interface/src/instruction.rs
Ironically #155 missed the vital part: The authority being a signer.
=> Marks the authority in `extend_program_checked()` as signer

instruction/Cargo.toml, instruction/src/lib.rs, instruction/src/syscalls.rs, program/Cargo.toml, program/src/instruction.rs
Currently the syscalls module on the `instruction` crate is behind a `#[cfg(target_os = "solana")]` attribute. Therefore, they are not "visible" on non-solana environment. This makes it difficult to write code that depends on them. Additionally, the crate does not include helpers to wrap the syscalls into friendlier functions.
Add a `syscalls` feature to the crate to conditionally include the syscalls module and add wrapper functions for the syscalls. This PR also update the `solana-program` crate to use these helpers to avoid duplication of logic.
=> instruction: Add syscalls helpers

define-syscall/src/lib.rs
Currently the define-syscall crate is `no_std` "friendly" but does not have the crate attribute. This indirectly brings the `std` at link stage when trying to compile `no_std` programs:
```
error[E0152]: found duplicate lang item `panic_impl`
--> src/lib.rs:9:1
|
9 | pinocchio::nostd_panic_handler!();
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: the lang item is first defined in crate `std` (which `solana_define_syscall` depends on)
```
Add the `#![no_std]` attribute to the crate.
=> define-syscall: Add `no_std` attribute

Cargo.lock, bls/Cargo.toml, bls/src/error.rs, bls/src/lib.rs, bls/src/pod.rs
Just reorganizing some trait implementations for BLS pod types
- Derived `Ord` and `PartialOrd` for all the pod types
- Created serde feature and made the serde serialization/deserialization optional
- Created bytemuck feature and made the bytemuck implementation optional
- Created `frozen-abi` feature and implemented the `AbiExample` traits for the bls pod types
- Implemented `Display` and `FromStr` for bls pod types
=> [bls] Add `serde`, `bytemuck` and `frozen-abi` features

Cargo.lock, bls/Cargo.toml
Downstream projects that depend on specific versions of Solana crates don't play well with the bls crate that uses the Solana sdk crates in master. Fixing the dependencies to the ones currently in crates.io while bls is active in development.
=> [bls] Fix dependencies to crate versions for now

keypair/src/lib.rs
The `generate()` function on `Keypair` exposes a public dependency on `rand` because it requires certain types from the crate. Using the public type from an external crate in our interface means that we can't upgrade without breaking downstream users.
Mark the function as deprecated, and provide a new way to create a random keypair using `new_from_array`.
Unfortunately, we can't mark the function as `const` because the dalek types don't have const constructors.
=> keypair: Deprecate `generate` to avoid public rand dep

feature-gate-interface/src/lib.rs
The feature gate interface's `Feature` API allows for serializing and deserializing a `Feature { activated_at: Option<u64> }` within account state. However, this can be a little flaky when it comes to attempting to set that `Option<u64>` value to `Some`.
For example, if you create an account under `Feature111...` with only 1 byte, it will deserialize just fine into `Feature { activated_at: None }`, but if you attempt to set the slot value to `Some`, it will fail to serialize.
Since the API already enforces some special-casing about account ownership, and declares a constant `size` function, it makes sense for it to also enforce account data length on either side of the serialization workflow.
=> feature-gate-interface: check account data len on deserialize

sdk/src/net.rs
this never should have been public interface in the first place
=> mark net::DEFAULT_TPU_COALESCE deprecated

instructions-sysvar/src/lib.rs
There are no checks for the instructions sysvar data length before trying to subtract / store data into the account. This does not cause issues in production, but causes issues with Firedancer's fuzzing efforts as this code triggers a panic if the sysvar account is not correctly initialized by the fuzzer when testing UB.
=> sysvar-instructions: check data length before storing current instruction idx

instructions-sysvar/src/lib.rs, program/src/sysvar.rs
Whoopsie, changes #162 to be non-breaking so we can just cut a patch version. We can still make Agave use the new, non-deprecated method.
=> instructions-sysvar: refactor #162 to be non-breaking

fee-structure/src/lib.rs, genesis-config/src/lib.rs, native-token/src/lib.rs
The `sol_to_lamports` and `lamports_to_sol` functions are problematic because they use floats, which are not precise.
Deprecate the functions, and add versions that use strings instead.
Added @tao-stones to check the `FeeStructure` change -- it looks like `FeeStructure::new` is only used in one test.
=> native-token: Deprecate float usage, add str usage

clock/src/lib.rs
Mainnet activated the feature to use the `UPDATED_HASHES_PER_SECOND_6` and `UPDATED_HASHES_PER_TICK6` values to control hashing a long time ago. We're past due to deprecate these old values and make the `DEFAULT*` values match the ones we actually use in mainnet/testnet/etc.
=> retire updated hashes consts

account-info/src/lib.rs
Only a minuscule amount of transactions grows accounts. Zeroing out 10 KiB for every instruction account in every instruction (including CPI) of every transaction just in case is quite wasteful. It would make more sense to only do this on demand and have programs pay for what they use.
This change makes sure that programs always call `sol_memset()` to communicate to the program runtime that they wish to grow an account and access the new space even before the next CPI or the end of the current instruction.
=> Deprecates `AccountInfo::realloc()`

Cargo.toml
As noticed in #175, some of the intra-repo dependencies are too low, so the crates don't properly declare their minimum supported versions.
Bump the required dependencies. I will wait to land this until after #181 and a failing publish on solana-keypair.
=> Bump versions for publish

program-entrypoint/src/lib.rs, program-memory/src/lib.rs, program/src/instruction.rs, scripts/build-sbf.sh, secp256r1-program/src/lib.rs
When building certain crates with `cargo build-sbf`, we generate warnings currently, which isn't great for downstream users.
Fix the warnings, and make CI stricter by forbidding warnings.
=> sbpf: Fix various build warnings

.github/workflows/publish-rust.yml
The YAML file apparently isn't parsable: https://github.com/anza-xyz/solana-sdk/actions/runs/15467354813
Remove the quotes around the args, which seems to help pass a check.
=> CI: Fix git cliff command again

Cargo.lock, Cargo.toml
The minimal versions check is now failing when building the toml crate.
Bump the toml crate to the newest version, which seems to resolve the issue. No other version worked.
=> Bump toml version to 0.8.23 for minimal versions

Cargo.lock, Cargo.toml, frozen-abi/Cargo.toml, frozen-abi/src/abi_example.rs
Needed by https://github.com/anza-xyz/agave/pull/3796
=> Add AbiExample for dashmap and boxcar

msg/Cargo.toml, msg/src/lib.rs
In a follow-up PR I'd like to move `sol_log_data` here as I noticed it gets used in a few places
Note: this is a breaking change
=> msg!: make std optional

quic-definitions/src/lib.rs
As the change to increase QUIC connection timeout has been released. Now we can afford to reduce the frequency to send QUIC keep-alive messages.
The interval is changed from 1 s to 45 seconds
This to follow up on https://github.com/anza-xyz/solana-sdk/pull/29.
=> Increase quic heartbeat interval to 45 second to reduce overhead

.github/workflows/publish-rust.yml
The publish job against maintenance/v2.x failed to generate a changelog because we look for changes to `master`, but we really want changes up to the current HEAD: https://github.com/anza-xyz/solana-sdk/actions/runs/15971057246/job/45042369237
Use `HEAD` instead of `master`.
NOTE: this isn't technically needed because it's targeting master, but the next PR will target the maintenance branch.
=> CI: Fixup git-cliff step for non-master branches

.github/workflows/publish-rust.yml
The publish job against maintenance/v2.x failed to generate a changelog because we look for changes to `master`, but we really want changes up to the current HEAD.
Use `HEAD` instead of `master`.
=> v2: CI: Fixup git-cliff step for non-master branches

Cargo.lock, Cargo.toml, base3-encoding/Cargo.toml, base3-encoding/src/lib.rs
This PR introduces the solana-base3-encoding crate, created to efficiently encode Alpenglow vote certificates.
Alpenglow certificates contain aggregate signatures, which don't specify individual signers. For simple certificate types like Finalize or Notarize, a bit vector is sufficient to identify the voters.
However, more complex certificates like NotarizeFallback or Skip can contain two different vote types. Using a separate bit vector for each type is not scalable. As the validator set grows to 4,000, the two bit vectors would exceed 1 KB, making certificates harder to fit in a single network packet. 
This crate provides a more compact encoding scheme. The design is tailored to the [CertificateMessage](https://github.com/solana-program/alpenglow-vote/blob/master/program/src/bls_message. …
=> [base3-encoding] Add solana base3 encoding crate

scripts/patch-crates-functions.sh
Base3 encoding crate was added in https://github.com/anza-xyz/solana-sdk/commit/50dfbd088c51b7229c67d432d8c8801dafaa7904, but I forgot to add it the patch crates script.
Add it to the script.
=> Add base3-encoding to `patch-crates-functions.sh`

bls-signatures/src/pubkey.rs, bls-signatures/src/signature.rs
The signature and proof of possession verification interface was made more generic and flexible in https://github.com/anza-xyz/solana-sdk/pull/202, but the public key and signature aggregation still only works for the `PubkeyProjective` and `SignatureProjective` types.
I made two improvements to the BLS aggregation interface:
[1736017](https://github.com/anza-xyz/solana-sdk/pull/213/commits/17360174ed800deb2bdc1fba7deedd3abdeea0b3): The `aggregate` and `aggregate_with` functions for `PubkeyProjective` and `SignatureProjective` have been updated to support any of projective, affine, and compressed types. I added a `?Sized` bound to also support `Vec<&dyn AsPubkeyProjective>` and `Vec<&dun AsSignatureProjective>` input as well, so this should be quite ergonomic and flexible to use now. …
=> [bls-signature] Update the public key and signature aggregation function to be generic

Cargo.lock, base3-encoding/Cargo.toml, base3-encoding/benches/bitvec.rs, base3-encoding/benches/bytes.rs
Adding benches for the `base3-encoding` crate.
The following is the result of running benches on my m1 mac.
```
BitVec/encode/256       time:   [302.23 ns 302.43 ns 302.69 ns]
Found 11 outliers among 100 measurements (11.00%)
2 (2.00%) high mild
9 (9.00%) high severe
BitVec/decode/256       time:   [205.48 ns 205.56 ns 205.66 ns]
Found 15 outliers among 100 measurements (15.00%)
2 (2.00%) low mild
3 (3.00%) high mild
10 (10.00%) high severe
BitVec/encode/512       time:   [579.18 ns 579.46 ns 579.85 ns]
Found 16 outliers among 100 measurements (16.00%)
8 (8.00%) high mild
8 (8.00%) high severe
BitVec/decode/512       time:   [375.45 ns 375.79 ns 376.29 ns]
Found 15 outliers among 100 measurements (15.00%)
2 (2.00%) high mild
13 (13.00%) high severe
BitVec/encode/1024      time:   [1.1601 …
```
=> [base3-encoding] Add benches

program/src/lib.rs
The initial [link](https://solana.com/docs/programs/lang-rust#restrictions) is broken
This PR updates the link to use [this](https://solana.com/docs/programs/limitations#rust-libraries) which seems to be the correct one
=> doc: update modified rust std lib link

vote-interface/src/state/mod.rs, vote-interface/src/state/vote_state_0_23_5.rs, vote-interface/src/state/vote_state_1_14_11.rs, vote-interface/src/state/vote_state_v3.rs, vote-interface/src/state/vote_state_versions.rs
In preparation for introducing a new vote state (v4), this PR renames `vote_state_v3::VoteState` to `vote_state_v3::VoteStateV3`.
Normally, the module path could serve as the differentiator (ie. `vote_state_v3::VoteState` and `vote_state_v3::VoteState`), but that's brittle and we re-exported `VoteState`.
@joncinque I wanted to get your opinion on how best to handle this breaking change, as well as subsequent breaking changes to `VoteStateVersions`. We could introduce this change here as a minor release, where we mark the previous re-export as deprecated:
```rust
#[deprecated(..)]
pub use vote_state_v3::VoteStateV3 as VoteState;
pub use vote_state_v3::VoteStateV3;
```
However, since we plan to nuke `VoteStateVersions`, I wonder if the whole thing is ok to do in a major.
See #206
=> vote-interface: rename `VoteState` to `VoteStateV3`

.github/workflows/backport.yml, README.md
There's a maintenance branch for v2 crates in the SDK repo called `maintenance/v2.x`, but there's no way to automatically backport PRs to that branch.
Copy / paste how Kit does things and include a backporting job.
There's also some new info about the maintenance branch and how to perform backports.
=> CI: Add backport workflow and info

Cargo.lock, instruction/src/account_meta.rs, instruction/src/wasm.rs, sdk-wasm-js/Cargo.toml, sdk-wasm-js/src/lib.rs, sdk-wasm-js/tests/transaction.mjs
While working on the refactor of all wasm-js logic into sdk-wasm-js, I noticed that no matter what I did, `SystemInstruction` still made it into the final build. That made it impossible to build the package with breaking changes.
Remove the usage of `SystemInstruction` in the tests. This required exposing `Instruction` and `AccountMeta` through wasm-bindgen to be able to create instructions.
The API doesn't need to be perfect, just usable, so I went with a builder pattern for adding `AccountMeta`s to an `Instruction`, which hugely simplifies the logic. Otherwise we'd need to perform conversions between JS arrays and `Vec<AccountMeta>`, which I was too lazy to do properly because wasm-js crate is more of a proof-of-concept.
While doing that, I moved the wasm-js deps to the component crates …
=> wasm-js!: Remove system program dependency

Cargo.lock, client-traits/Cargo.toml, message/Cargo.toml, message/src/compiled_keys.rs, message/src/inline_nonce.rs, message/src/legacy.rs, message/src/lib.rs, message/src/sanitized.rs, transaction/Cargo.toml, transaction/src/lib.rs, transaction/src/versioned/mod.rs
While debugging changes to the wasm-js build, I noticed that `solana-transaction` and `solana-message` were pulling in `solana-system-interface` in a lot of situations, even though there's a lot of code in place to make sure that doesn't happen.
Totally remove the dependency on solana-system-interface by inlining some nonce-related code in solana-message.
=> message / transaction: Remove dependency on solana-system-interface

instructions-sysvar/src/lib.rs
This patch fixes the inaccuracies in the memory layout description for the `serialize_instructions` function.
Specifically, it addresses incorrect byte offsets (e.g. incorrect starting offset for table of sets) and not taking variable number of accounts into consideration.
=> docs: fix memory layout comment in instructions sysvar

Cargo.toml
The SDK repo provides libraries, which should allow downstream users some flexibility when choosing what dependencies they want to use. However, we currently pin two dependencies: array-bytes and ed25519-dalek.
Unpin both of them!
array-bytes is only used in tests, so it shouldn't have any impact. ed25519-dalek is definitely more sensitive, but Agave and other downstream users should decide what version they want to use, and we shouldn't force that at the library level.
=> deps: Unpin array-bytes and ed25519-dalek

account/src/lib.rs, program/src/sysvar.rs, sysvar/src/clock.rs, sysvar/src/epoch_rewards.rs, sysvar/src/epoch_schedule.rs, sysvar/src/fees.rs, sysvar/src/last_restart_slot.rs, sysvar/src/lib.rs, sysvar/src/program_stubs.rs, sysvar/src/recent_blockhashes.rs, sysvar/src/rent.rs, sysvar/src/rewards.rs, sysvar/src/slot_hashes.rs, sysvar/src/slot_history.rs, sysvar/src/stake_history.rs
Problem: the Sysvar trait relies on bincode, but most of the time people just want `Sysvar::get` which doesn't rely on bincode
~Solution: make a `SysvarGet` trait that has one method: `get`. Make the `Sysvar` trait use `SysvarGet::get`. Annoyingly this is still technically a breaking change because we are adding a constraint to `Sysvar`, but for the vast majority of users nothing should break~
Solution: move the other methods out of `Sysvar` and into a new `SysvarSerialize` trait
=> move less important methods from Sysvar to SysvarSerialize

.github/workflows/main.yml, scripts/test-doc.sh, sdk-wasm-js/Cargo.toml, secp256k1-program/Cargo.toml
The doctests for secp256k1-program fail when run on the crate individually because of a missing feature declaration on `solana-keccak-hasher`.
Add the feature. At the same time, run the doctests with `cargo-hack` to catch these in the future.
The sdk-wasm-js package fails to run doctests because it doesn't have an rlib target, so add that too.
=> secp256k1-program: Fix doc tests

.github/workflows/main.yml
This is a manual backport of #217
It seems like openssl 3.4.1 is removed from SLProWeb and the clippy ci is failing. I saw that this was fixed in the monorepo as well in https://github.com/anza-xyz/agave/pull/6804 and https://github.com/anza-xyz/agave/pull/6824.
I followed https://github.com/anza-xyz/agave/pull/6824 to use vcpkg to install openssl for windows.
=> [ci] Use vcpkg to install openssl for windows (#217)

program/src/hash.rs, sha256-hasher/src/lib.rs
As mentioned in anza-xyz/agave#7028, the `extend_and_hash` function is unnecessary and creates another allocation, so we inlined it in Agave.
Since it's been properly marked as deprecated, remove it.
=> sha256-hasher: Remove `extend_and_hash`

Cargo.lock, Cargo.toml, bls-signatures/Cargo.toml, bls-signatures/benches/bls_signatures.rs, bls-signatures/src/pubkey.rs, bls-signatures/src/signature.rs
The bls-signatures crate do not yet support parallelization.
I took a stab at adding parallelization support via rayon.
- I added the `parallel` feature
- under the `parallel` feature, I added the `par_aggregate`, `par_aggregate_with`, and `par_aggregate_verify` functions that uses rayon for summing up the public keys or signatures
- in the process, the lifetimes and the iterator syntax was getting out of hand, so I ended up simplifying the api so that these functions take in slices of pubkeys or signatures instead of iterators
- one thing to note is that the standard `aggregate`, `aggregate_with`, and `aggregate_verify` functions have `dyn` type support while their parallel analogue do not. I did this on purpose to really make the parallel versions as fast as possible.
I ran some benches …
=> [bls-signatures] Add `parallel` feature and use `rayon` for aggregating pubkeys and signatures

instruction-error/Cargo.toml, instruction-error/src/lib.rs, message/Cargo.toml, program-error/Cargo.toml, program-error/src/lib.rs
The instruction-error and program-error crates have `std` features in Cargo.toml that don't do anything
=> {instruction,program}error!: remove unused std features

address/src/error.rs
The `ParseAddressError` enum is only needed if the `decode` feature is enabled, but it's currently included in all cases.
Gate `ParseAddressError` on the `decode` feature.
=> address: Gate `ParseAddressError` on `decode` feature

rent-collector/src/lib.rs
As noted in #226, the rent collector crate and struct are no longer needed, and with https://github.com/anza-xyz/agave/pull/7297, will no longer be used.
Mark the crate as deprecated, so that we can backport and release the change, then delete the crate entirely.
=> rent-collector: Deprecate the crate

Cargo.lock, Cargo.toml, scripts/build-sbf.sh, scripts/test-wasm.sh, system-interface/Cargo.toml, system-wasm-js/.gitignore, system-wasm-js/Cargo.toml, system-wasm-js/package.json, system-wasm-js/src/lib.rs
The system interface used to include wasm-js bindings for the instruction creators, which was a problem for non-JS wasm builds, as described at https://github.com/solana-program/system/issues/47.
Add the wasm-js bindings as an external crate, similar to the work done with sdk-wasm-js.
Fixes https://github.com/solana-program/system/issues/47
Closes https://github.com/solana-program/system/pull/48
=> system-wasm-js: Introduce crate for exposing wasm-js instructions

vote-interface/src/state/mod.rs, vote-interface/src/state/vote_state_0_23_5.rs, vote-interface/src/state/vote_state_1_14_11.rs, vote-interface/src/state/vote_state_v3.rs, vote-interface/src/state/vote_state_versions.rs
Simply renames "current" in each of the `VoteStateVersions` API to "v3".
Paves the way for the introduction of v4 in `VoteStateVersions`.
=> vote-interface: rename current to v3

Cargo.lock, signature/Cargo.toml, signature/src/lib.rs
I currently find myself converting to the raw bytes to use bytemuck, so this would be nice to have
=> signature: add optional bytemuck support

bls-signatures/benches/bls_signatures.rs, bls-signatures/src/keypair.rs, bls-signatures/src/macros.rs, bls-signatures/src/proof_of_possession.rs, bls-signatures/src/pubkey.rs, bls-signatures/src/signature.rs
The current signature verification function takes in the projective form of the public key and signatures. This is a bit inefficient since the public keys and signatures are typically going to be sent over the network in their affine form. In order to invoke the verification function, we have to currently convert them to their projective form just to call the verification function. The verification function would then immediately convert them back to affine internally before performing the pairing operation.
I made the following changes:
- Updated verification API: The core verification functions, including `verify_signature` and the parallel batch verifiers, now directly accept the more efficient affine types (`Pubkey`, `Signature`). This removes the needless conversions and make the API …
=> [bls-signatures] Use affine for `Keypair` and signature verification

bn254/src/addition.rs, bn254/src/compression.rs, bn254/src/lib.rs, bn254/src/multiplication.rs, bn254/src/pairing.rs
The logic in `lib.rs` is becoming slightly harder to read as it is getting longer and it is organized by submodules inside files.
I created logical submodules for the `addition`, `multiplication`, and `pairing` operations for elliptic curves. I then moved the relevant logic in `lib.rs` to these relevant submodules. All the functions and constants in `lib.rs` were behind private submodules (`consts` and `target_arch`) and were re-exported as part of `prelude`. I kept this structure the same, so from the perspective of downstream projects, this should not introduce any visible changes.
=> [bn254] Refactor out addition, multiplication, and pairing into separate modules

vote-interface/src/state/vote_state_0_23_5.rs, vote-interface/src/state/vote_state_1_14_11.rs, vote-interface/src/state/vote_state_v3.rs, vote-interface/src/state/vote_state_v4.rs, vote-interface/src/state/vote_state_versions.rs
* use the custom `VoteState` parser for all targets
* add `is_uninitialized()` to `VoteState` structs, for agave code that skips `VoteStateVersions`
* fix a bug where `(0, Pubkey::default())` was added to `AuthorizedVoters`
=> vote-interface: enable parser on not(solana)

bls-signatures/benches/bls_signatures.rs, bls-signatures/src/pubkey.rs, bls-signatures/src/signature.rs
Currently, there is no public function to a batch of BLS signatures on different messages.
I added `batch_verify` and `par_batch_verify` functions to verify signatures on different messages.
After I added these functions, I realized that there are many different functions to verify different combination of signatures on messages, which could be quite confusing for developers. I ended up just removing the existing `par_verify_batch` and `par_verify_batch_binary_search` functions.
Now, the exposed API is quite simple. The `aggregate_verify` and `par_aggregate_verify` functions verify BLS signatures on the same message. The `batch_verify` and `par_batch_verify` functions verify BLS signatures on different messages.
=> [bls-signatures] Add batch signature verification functions on different messages

address/src/lib.rs
In some cases, comparing addresses (`[u8;32]` arrays) with the equality operator (`==`) results in "bloated" code, which eventually leads to an increased CU consumption.
This PR adds a custom `PartialEq` implementation to `Address`, which compares its value as a sequence of `u64` values.
=> address!: Add custom `PartialEq` impl

address/src/lib.rs, address/src/syscalls.rs, scripts/check-nits.sh
Currently the `Address::log` implementation is behind the "curve25519" and "syscalls" features. While this works for programs, it is overly restrictive when in "std" context.
Move the "std" specific implementation so that it is gated on the "std" feature only.
=> address!: Log visibility

address/src/lib.rs
Currently, the `PDA_MARKER` constant is not public and available only behind the "sha2" feature. This prevents helpers to used when providing an alternative way to derive PDAs.
Make the constant public.
=> address!: Make `PDA_MARKER` public

Cargo.lock, sdk-wasm-js/Cargo.toml, sdk-wasm-js/src/address.rs, sdk-wasm-js/src/hash.rs, sdk-wasm-js/src/instruction.rs, sdk-wasm-js/src/keypair.rs, sdk-wasm-js/src/transaction.rs, sdk-wasm-js/tests/address.mjs, sdk-wasm-js/tests/hash.mjs, sdk-wasm-js/tests/keypair.mjs, sdk-wasm-js/tests/transaction.mjs
The `solana-sdk-wasm-js` crate contain several functions that copy an outside-controlled JS data into WebAssembly memory before validating the input's size. This "copy-before-validate" can lead to excessive memory growth when oversized data are provided as input.
I went through the crate to added length checks for all the functions that "copy-before-validate".
- `hash.rs`: This was pretty straightforward. I just added length check if the value that is provided to the constructor does not match the expected hash bytes (32 bytes).
- `keypair.rs`: I updated the API of `fromBytes` function to directly take in a `Uint8Array` instead of a bytes slice. 
When a function exported via #[wasm_bindgen] accepts a byte slice (&[u8]) argument, wasm-bindgen generates JavaScript glue code. This glue code …
=> [sdk-wasm-js] Add length check on type conversion

commitment-config/Cargo.toml, commitment-config/src/lib.rs, scripts/check-no-std.sh
`solana-commitment-config` crate is not `no_std` when it's no_std-friendly
- make `solana-commitment-config` as `no_std` crate
- disable default (std) features for `serde` dependency
=> feat: add `no_std` support for commitment-config crate

Cargo.toml, program-entrypoint/Cargo.toml, program-entrypoint/src/lib.rs, program/Cargo.toml, secp256k1-program/Cargo.toml, sysvar/Cargo.toml
The solana-msg crate is brought in with default features, which makes it impossible to make downstream users of the crate no-std.
Add `default-features = false` for solana-msg at the workspace-level, and add the std feature to solana-program, which is the only place that requires it.
As part of this, I noticed that solana-program-entrypoint re-exports msg, but the re-export is never used, so I removed it.
=> msg: Use dependency without default features
